name: Deploy IDS projects website

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: 'Log level'     
    #     required: true
    #     default: 'warning'

jobs:
  # test-build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build the Docker image
  #     run: docker build -t ids-projects-website .

  deploy:
    # needs: test-build
    runs-on: [self-hosted, linux, X64, node2]
    #runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy website using docker-compose up
      run: docker-compose up --build -d
