name: Get data from GitHub GraphQL API
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/get-github-data.yml'
    - 'get_github_data/query_graphql.py'
  schedule:
    - cron:  '00 03,13 * * *'
    # Everyday at 03:00am and 13:00

jobs:
  query-graphql:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # Important part here (can be reused to run locally):
    - name: Install Python dependencies
      run: |
        python -m pip install -r get_github_data/requirements.txt
    - name: Query GitHub GraphQL API with Python
      env:
        GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
      run: |-
        python get_github_data/query_graphql.py
        cat assets/ids_github_data.json

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "vincent.emonet@gmail.com"
        git config --global user.name "Vincent Emonet"
        git add -A
        git commit -m "Update GitHub JSON data content" || exit 0
        git push
